### ISSUE TITLE
Add support for iOS 13

### ISSUE THREAD

**Issue by ghost** [aydenp/Ultrasound#8]
iPhone X (10,3)

iOS 13.2.2

Checkra1n 0.9.5

**Comment by aydenp** [comment]
While I wasn't initially intending to add support for iOS 13 to Ultrasound, due to Apple's new volume HUD (which I really like!), I've gotten [a lot of requests for it](https://twitter.com/aydenpanhuyzen/status/1199386728391495681) since checkra1n dropped, so I've decided to reconsider. This is now a priority for the next release.

**Comment by aydenp** [comment]
I've pushed a commit on the support/ios13 branch that adds preliminary support for iOS 13. Most things work. The main thing that doesn't is OLED mode, which will take some significant effort to fix.

**Comment by ghost** [comment]
Thanks, now its working fine in iOS 13 iPX, I don't really care about OLED mode so its okay

have a nice day
