### ISSUE TITLE
Add support for older iOS and 32-bit devices

### ISSUE THREAD

**Issue by Darthagnon** [aydenp/Ultrasound#9]
Would it be possible to add support for e.g. iOS 7 and iPhone 4S to Ultrasound? I'd love to use a better volume HUD, but afaik there are no tweaks like this that support older devices.

**Comment by aydenp** [comment]
Due to the APIs currently required by Ultrasound, this is not an enhancement request that is deemed in scope for the project. I appreciate your request, but unfortunately it would permanently slow progress on the tweak for newer versions. While others are free to create forks doing so, they won't be merged upstream due to the negative effect they would have on the source.
